### ISSUE TITLE
 بسم الله الرحمن الرحيم is not a verse

### ISSUE THREAD

**Issue by msal4** [aqeel371/QuranJson#2]
`verse_0` of every Surah is  `بسم الله الرحمن الرحيم` which is wrong since it's not a verse and should immediately start with `verse_1`

**Comment by Suleman-Elahi** [comment]
Its at 0 index so it doesn't matter !!!

**Comment by aqeel371** [comment]
@msal4 it is 0 index..you can skip this while parsing and if you need it with translation you can use it as it is
